Repository AY2223S1-CS2103-F13-3/tp, pull requests merged in 2022-10, with the labels that each got.

#21 Implement Find Tag function
  src/main/java/seedu/address/logic/commands/FindTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindTagCommandParser.java
  src/main/java/seedu/address/model/person/TagsContainKeywordPredicate.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: Story, Priority High

#26 Modify constructor for Meeting and created UniqueMeetingList to handle meetings
  docs/AboutUs.md
  docs/team/images/darren.png
  src/main/java/seedu/address/logic/commands/CreateMeetingCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/UniqueMeetingList.java
  src/main/java/seedu/address/model/meeting/exceptions/DuplicateMeetingException.java
  src/main/java/seedu/address/model/meeting/exceptions/MeetingNotFoundException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: Story, Priority High

#31 Add person to meeting
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddPersonToMeetingCommand.java
  src/main/java/seedu/address/logic/commands/CreateMeetingCommand.java
  src/main/java/seedu/address/logic/parser/AddPersonToMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/UniqueMeetingList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: Enhancement, Priority Medium

#32 Fix bugs that affected parsing of new command to create meetings, handle exceptions due to incorrect user input
  src/main/java/seedu/address/logic/commands/CreateMeetingCommand.java
  src/main/java/seedu/address/logic/parser/CreateMeetingCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/util/DateTimeProcessor.java
Labels: Bug, Priority High

#42 Implement Delete person from meeting functionality
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/CreateMeetingCommand.java
  src/main/java/seedu/address/logic/commands/DeletePersonFromMeetingCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeletePersonFromMeetingCommandParser.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
Labels: Enhancement, Priority Medium

#34 Create unit tests in AddressBookParserTest, CreateMeetingCommandParserTest and CreateMeetingCommandTest
  docs/DeveloperGuide.md
  docs/team/darrentde.md
  docs/team/genfusion122.md
  docs/team/tinenhao.md
  src/main/java/seedu/address/logic/commands/CreateMeetingCommand.java
  src/main/java/seedu/address/logic/parser/CreateMeetingCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/UniqueMeetingList.java
  src/main/java/seedu/address/model/util/DateTimeProcessor.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/MeetingCard.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateMeetingCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CreateMeetingCommandParserTest.java
  src/test/java/seedu/address/model/meeting/MeetingTest.java
  src/test/java/seedu/address/testutil/MeetingBuilder.java
Labels: Task, Priority High

#46 Implemented EditMeetingCommand
  build.gradle
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/EditMeetingCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditMeetingCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CreateMeetingCommandTest.java
Labels: Enhancement, Priority Medium

#52 Enhance Find Meeting Command
  src/main/java/seedu/address/logic/commands/FindMeetingCommand.java
  src/main/java/seedu/address/logic/parser/FindMeetingCommandParser.java
  src/main/java/seedu/address/model/meeting/MeetingContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/util/FindMeetingFunctionalInterface.java
Labels: Enhancement, Priority Medium

#60 Fix add/delete person
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddPersonToMeetingCommand.java
  src/main/java/seedu/address/logic/commands/DeletePersonFromMeetingCommand.java
Labels: Enhancement, Priority Medium

#64 Added more examples for meeting sample and enforce date time in creation of new meetings
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/util/DateTimeProcessor.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: Enhancement, Priority Medium

#63 Implement new feature to delete meetings
  src/main/java/seedu/address/logic/commands/DeleteMeetingCommand.java
  src/main/java/seedu/address/logic/parser/DeleteMeetingCommandParser.java
Labels: Enhancement, Priority Medium

#70 UG update
  README.md
  docs/UserGuide.md
  docs/images/UiUpdate.png
Labels: Task, Priority High

#75 Enhance new meeting parser (new branch)
  src/main/java/seedu/address/logic/commands/CreateMeetingCommand.java
  src/main/java/seedu/address/logic/commands/EditMeetingCommand.java
  src/main/java/seedu/address/logic/parser/CreateMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/EditMeetingCommandParser.java
  src/main/java/seedu/address/model/util/DateTimeProcessor.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedMeeting.java
  src/test/java/seedu/address/logic/commands/EditMeetingCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/EditMeetingCommandParserTest.java
  src/test/java/seedu/address/model/meeting/MeetingTest.java
  src/test/java/seedu/address/testutil/EditMeetingDescriptorBuilder.java
  src/test/java/seedu/address/testutil/MeetingBuilder.java
  src/test/java/seedu/address/testutil/TypicalMeetings.java
Labels: Bug, Priority High, Severity Medium
